title: Helix Bridge Doc
description: The documentation of Helix Bridge
theme: just-the-docs

url: https://wuminzhe.github.io/helixdocs

aux_links:
  Docs Repo: https://github.com/helix-bridge/helix-docs

# color_scheme: dark

callouts:
  note:
    title: Note
    color: yellow
