title: Helix Bridge Docs
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://helixbridge.app/

aux_links:
  HelixBridge: https://helixbridge.app/
  # Github: https://github.com/helix-bridge/helix-docs

callouts:
  note:
    title: Note
    color: yellow
